services:
  master:
    container_name: master
    build: master
    ports:
      - "8080:8080"
    networks: 
      - my-net
  secondary1:
    container_name: secondary1
    build: secondary2
    command: [ "1" ]
    ports:
      - "8081:8081"
    networks:
      - my-net
    depends_on:
      - master
  secondary2:
    container_name: secondary2  
    build: secondary2
    command: [ "2" ]
    ports:
      - "8082:8082"
    networks:
      - my-net
    depends_on:
      - master
networks:
  my-net:

