services:
  master:
    container_name: master
    build: .
    image: replicated_log
    volumes:
      - type: bind
        source: ./master.py
        target: /app/master.py
    command: [ "./master.py" ]    
    ports:
      - "8080:8080"
    networks: 
      - my-net
  secondary1:
    container_name: secondary1
    build: .    
    image: replicated_log    
    volumes:
      - type: bind
        source: ./secondary.py
        target: /app/secondary.py
    command: [ "./secondary.py", "1" ]
    ports:
      - "8081:8081"
    networks:
      - my-net
    depends_on:
      - master
  secondary2:
    container_name: secondary2  
    build: .    
    image: replicated_log
    volumes:
      - type: bind
        source: ./secondary.py
        target: /app/secondary.py    
    command: [ "./secondary.py", "2" ]
    ports:
      - "8082:8082"
    networks:
      - my-net
    depends_on:
      - master
networks:
  my-net:

